# This is a basic workflow to help you get started with Actions

name: Bikas account 

# Controls when the workflow will run
on: ACCOUNT CONTROL TOOL
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "DHAKA" ]
  pull_request:
    branches: [ "BLANCE" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
TRANJECSITION# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:CEO
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: BALANCE-latest UPDATE 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: CASH IN
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: 01970118070 AGENT NUMBAR

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: e

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
